/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.telas;

/**
 *
 * @author Michael
 */
import br.com.controller.CampeonatoController;
import br.com.bean.Campeonato;


public class ConsultaCampeonato extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaCampeonato
     */
    public ConsultaCampeonato() {
        initComponents();
        preencherCbNomeCampeonato();

    }

    CampeonatoController campControl = new CampeonatoController();

    public void preencherCbNomeCampeonato() {
        cbNomeCampeonato.addItem("Selecione");
        for (String nome : campControl.consultaNomeCampeonato()) {
            cbNomeCampeonato.addItem(nome);
        }
    }

    public void preencherLabelCampeonato() {
        if (!cbNomeCampeonato.getSelectedItem().toString().equals("Selecione")) {
            Campeonato campeonato = new Campeonato();
            campeonato = campControl.consultaCampControl(cbNomeCampeonato.getSelectedItem().toString());

            lblQtdEquipes.setText(String.valueOf(campeonato.getQtdEquipe()));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblQtdEquipes = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        cbNomeCampeonato = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(660, 541));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Numero de Equipes:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Consulta de Campeonato");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        lblQtdEquipes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQtdEquipes.setText("...");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cbNomeCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeCampeonatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQtdEquipes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNomeCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnPesquisar)
                    .addComponent(cbNomeCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblQtdEquipes))
                .addGap(382, 382, 382))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (!cbNomeCampeonato.getSelectedItem().toString().equals("Selecione")) {
            preencherLabelCampeonato();
        } else {

            lblQtdEquipes.setText("...");

        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cbNomeCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeCampeonatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomeCampeonatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbNomeCampeonato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblQtdEquipes;
    // End of variables declaration//GEN-END:variables
}
