package br.com.telas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Campeonato = new javax.swing.JMenu();
        cadastroCampeonato = new javax.swing.JMenuItem();
        classificacaoCampeonato = new javax.swing.JMenuItem();
        cadastroEquipe = new javax.swing.JMenuItem();
        editarCampeonato = new javax.swing.JMenuItem();
        excluirCampeonato = new javax.swing.JMenuItem();
        consulta = new javax.swing.JMenu();
        cadastarEquipe = new javax.swing.JMenuItem();
        consultaEquipe = new javax.swing.JMenuItem();
        editarEquipe = new javax.swing.JMenuItem();
        excluirEquipe = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        Campeonato.setText("Campeonato");

        cadastroCampeonato.setText("Cadastro");
        cadastroCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCampeonatoActionPerformed(evt);
            }
        });
        Campeonato.add(cadastroCampeonato);

        classificacaoCampeonato.setText("Realizar Campeonato");
        classificacaoCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificacaoCampeonatoActionPerformed(evt);
            }
        });
        Campeonato.add(classificacaoCampeonato);

        cadastroEquipe.setText("Consulta");
        cadastroEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroEquipeActionPerformed(evt);
            }
        });
        Campeonato.add(cadastroEquipe);

        editarCampeonato.setText("Editar");
        editarCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCampeonatoActionPerformed(evt);
            }
        });
        Campeonato.add(editarCampeonato);

        excluirCampeonato.setText("Excluir");
        excluirCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCampeonatoActionPerformed(evt);
            }
        });
        Campeonato.add(excluirCampeonato);

        jMenuBar1.add(Campeonato);

        consulta.setText("Equipe");

        cadastarEquipe.setText("Cadastro");
        cadastarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastarEquipeActionPerformed(evt);
            }
        });
        consulta.add(cadastarEquipe);

        consultaEquipe.setText("Consulta");
        consultaEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEquipeActionPerformed(evt);
            }
        });
        consulta.add(consultaEquipe);

        editarEquipe.setText("Editar");
        editarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEquipeActionPerformed(evt);
            }
        });
        consulta.add(editarEquipe);

        excluirEquipe.setText("Excluir");
        excluirEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEquipeActionPerformed(evt);
            }
        });
        consulta.add(excluirEquipe);

        jMenuBar1.add(consulta);

        sair.setText("Sair");
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCampeonatoActionPerformed
        CadastroDeCampeonato cadCampeonato = new CadastroDeCampeonato();
        cadCampeonato.setVisible(true);
        desktop.add(cadCampeonato);
    }//GEN-LAST:event_cadastroCampeonatoActionPerformed

    private void consultaEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEquipeActionPerformed
        ConsultaEquipe consEqui = new ConsultaEquipe();
        consEqui.setVisible(true);
        desktop.add(consEqui);
    }//GEN-LAST:event_consultaEquipeActionPerformed

    private void cadastroEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEquipeActionPerformed
        ConsultaCampeonato consultaCamp = new ConsultaCampeonato();
        consultaCamp.setVisible(true);
        desktop.add(consultaCamp);
    }//GEN-LAST:event_cadastroEquipeActionPerformed

    private void cadastarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastarEquipeActionPerformed
        CadastroDeEquipes cadEqui = new CadastroDeEquipes();
        cadEqui.setVisible(true);
        desktop.add(cadEqui);
    }//GEN-LAST:event_cadastarEquipeActionPerformed

    private void excluirCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCampeonatoActionPerformed
        ExcluirCampeonato excluCamp = new ExcluirCampeonato();
        excluCamp.setVisible(true);
        desktop.add(excluCamp);
    }//GEN-LAST:event_excluirCampeonatoActionPerformed

    private void editarCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCampeonatoActionPerformed
        EditarCampeonato  ediCamp = new EditarCampeonato();
        ediCamp.setVisible(true);
        desktop.add(ediCamp);
        
    }//GEN-LAST:event_editarCampeonatoActionPerformed

    private void classificacaoCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificacaoCampeonatoActionPerformed
       RealizarCampeonato realizar = new RealizarCampeonato();
       realizar.setVisible(true);
       desktop.add(realizar);
    }//GEN-LAST:event_classificacaoCampeonatoActionPerformed

    private void editarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEquipeActionPerformed
        EditarEquipes edEqui = new EditarEquipes();
        edEqui.setVisible(true);
        desktop.add(edEqui);
    }//GEN-LAST:event_editarEquipeActionPerformed

    private void excluirEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEquipeActionPerformed
        ExcluirEquipe excluEqui = new ExcluirEquipe();
        excluEqui.setVisible(true);
        desktop.add(excluEqui);
    }//GEN-LAST:event_excluirEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Campeonato;
    private javax.swing.JMenuItem cadastarEquipe;
    private javax.swing.JMenuItem cadastroCampeonato;
    private javax.swing.JMenuItem cadastroEquipe;
    private javax.swing.JMenuItem classificacaoCampeonato;
    private javax.swing.JMenu consulta;
    private javax.swing.JMenuItem consultaEquipe;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem editarCampeonato;
    private javax.swing.JMenuItem editarEquipe;
    private javax.swing.JMenuItem excluirCampeonato;
    private javax.swing.JMenuItem excluirEquipe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
